microsoft/winget-cli-restsource

- documentation/WinGet-1.0.0.yaml
- src/WinGet.RestSource/Constants/ApiConstants.cs
- Updating Rest API schema version to 1.0.0 as the changes to it are finalized.
> Update Rest Api schema version to 1.0.0

- documentation/WinGet-1.1.0.yaml
This is the pr to check in the official RestApi 1.1.0 spec.
The spec's been reviewed in #43
> RestApi 1.1.0 spec finalized

- src/WinGet.RestSource.Functions/InstallerFunctions.cs
- src/WinGet.RestSource.Infrastructure/README.MD
- src/WinGet.RestSource/Common/FormatJSON.cs
- src/WinGet.RestSource/Constants/ApiConstants.cs
- src/WinGet.RestSource/Constants/ErrorConstants.cs
- src/WinGet.RestSource/Cosmos/CosmosDataStore.cs
- src/WinGet.RestSource/Cosmos/CosmosDatabase.cs
- src/WinGet.RestSource/Cosmos/ICosmosDatabase.cs
Revising formatting to be consistent within files and correcting misspellings in comments/variables.
> Minor comment and formatting updates

- pipelines/templates/restore-build-publish-test.yml
- src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj
- src/WinGet.RestSource.UnitTest/WinGet.RestSource.UnitTest.csproj
- Azure function app has issues with .NET 5.0 target framework. Reverting the project to use .NET Core 3.1 as this is working properly.
> Update az functions to .net 3.1

- src/WinGet.RestSource.Functions/ServerFunctions.cs
- src/WinGet.RestSource.Functions/Startup.cs
- src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj
- src/WinGet.RestSource.Functions/local.settings.template.json
- src/WinGet.RestSource/Constants/CosmosConnectionConstants.cs
- src/WinGet.RestSource/Cosmos/CosmosDataStore.cs
- src/WinGet.RestSource/Cosmos/CosmosDatabase.cs
- src/WinGet.RestSource/Cosmos/CosmosDocument.cs
- src/WinGet.RestSource/Cosmos/ICosmosDatabase.cs
- src/WinGet.RestSource/Cosmos/ICosmosIdDocument.cs
- src/WinGet.RestSource/Exceptions/DefaultException.cs
- src/WinGet.RestSource/Models/ExtendedSchemas/CosmosPackageManifest.cs
- src/WinGet.RestSource/Models/Schemas/ManifestSearchRequest.cs
- src/WinGet.RestSource/WinGet.RestSource.csproj
The CosmosDB SDK has evolved quite a bit with the v3 major version. Updating to take advantage of latest features and security fixes.
> Updating to Azure Cosmos v3 SDK

- pipelines/templates/copy-and-publish-powershell.yml
Folder structure still undergoing some revisions....
> Revise folder structure per scripts

- Tools/PowershellModule/src/Library/Get-WinGetManifest.ps1
Single Application Manifest(s) only.
> Reset functionality of the Get-WinGetManifest (File) functionality

- Tools/PowershellModule/doc/PowerShell/Get-WinGetManifest.md
- Tools/PowershellModule/doc/PowerShell/Remove-WinGetManifest.md
- Tools/PowershellModule/doc/new-winget-rest-source-azure.md
> Update doc references to ManifestIdentifier

- Tools/PowershellModule/doc/new-winget-rest-source-azure.md
I have added a section for PowerShell prerequisites which helps resolve a number of errors experienced out of the box. This included installing the Azure Az module and ensures the correct Azure subscription is selected for deployment. (lines 24-45)
Further to this, I have tweaked the section (lines 55 to 70) to include the PowerShell cmdlet to unblock files. As its quite common for files to be blocked when downloading from the GitHub repo. I have also changed the order of the copy path line as the previous location was not best placed. 
I hope this helps.
> Documentation suggested enhancements to improve admin user experience

- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.int.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.pme.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.ppe.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.test.json
> Update Service Principal OIDs

- src/WinGet.RestSource.Infrastructure/Templates/KeyVaultConfiguration/keyvaultconfiguration.json
> Fix keyvaultconfiguration.json

- scripts/Release/winget_rotate_cosmosDB.ps1
This adds a script to automatically regenerate and rotate cosmos DB secrets
> Add Cosmos Secret Rotation Script

- Tools/PowershellModule/doc/new-winget-rest-source-azure.md
The click on Key Vault step is missing
> Step missing

- documentation/WinGet-1.4.0.yaml
The schema version is bumped to v1.4.0 to match winget client version.
This change includes all winget manifest changes since manifest v1.2.0.
> Add rest api schema 1.4.0

- documentation/WinGet-1.4.0.yaml
- src/WinGet.RestSource.Utils/Validators/EnumValidators/ExpectedReturnCodeResponseValidator.cs
https://github.com/microsoft/winget-cli/pull/2492#issuecomment-1235807256
I think this is all that needs to be done? But, if it isn't, please let me know
> Add ReturnResponse for PackageInUseByApplication to Validator Enum

- Tools/PowershellModule/src/Library/New-ARMObjects.ps1
- Tools/PowershellModule/src/Library/New-ARMParameterObject.ps1
> Fix   broken create experience keyvault

- documentation/WinGet-1.4.0.yaml
- src/WinGet.RestSource.Utils/Validators/EnumValidators/ExpectedReturnCodeResponseValidator.cs
* Related to microsoft/winget-cli#2635
> Support additional ExpectedReturnCodeResponses

- documentation/WinGet-1.0.0.yaml
- documentation/WinGet-1.1.0.yaml
- documentation/WinGet-1.4.0.yaml
- src/WinGet.RestSource.Utils/Models/Schemas/Installers.cs
This sets the node installer limit to 1024 to conform with client capabilities
> Update Installer Node Limit

- Tools/PowershellModule/src/Microsoft.WinGet.Source.psm1
- pipelines/templates/copy-and-publish-powershell.yml
- src/Microsoft.WindowsPackageManager.Rest/Microsoft.WindowsPackageManager.Rest.csproj
- src/WinGet.RestSource.IntegrationTest/WinGet.RestSource.IntegrationTest.csproj
- src/WinGet.RestSource.PowershellSupport/WinGet.RestSource.PowershellSupport.csproj
- src/WinGet.RestSource.Utils/WinGet.RestSource.Utils.csproj
This is to update the helper libs for powershell
> Update Helper LIb

- Tools/PowershellModule/src/Library/Classes.ps1
- documentation/WinGet-1.6.0.yaml
- src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj
- src/WinGet.RestSource.Utils/Models/Schemas/Installer.cs
First commit is a copy of existing 1.5 schema.
Changes are in the second commit.
> Add rest interface 1.6 and add DownloadCommandProhibited

- src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj
- src/WinGet.RestSource.Infrastructure/Templates/AzureFunction/azurefunction.json
This will fix the runtime issues and build issues
> Fix Runtime Issues and build problems

- Tools/PowershellModule/src/Library/Classes.ps1
- documentation/WinGet-1.7.0.yaml
- src/WinGet.RestSource.PowershellSupport/Helpers/PackageManifestUtils.cs
- src/WinGet.RestSource.Utils/Constants/ApiConstants.cs
- src/WinGet.RestSource.Utils/Models/Objects/InstallerSwitches.cs
- src/WinGet.RestSource.Utils/Models/Schemas/Installer.cs
- src/WinGet.RestSource.Utils/Validators/EnumValidators/RepairBehaviorValidator.cs
Microsoft Entra Id authentication support will be added later (investigation in progress).
For easier reviewing of doc changes, first commit is copy of 1.6 api doc. Second commit is 1.7 api doc update only.
> Update rest source doc to 1.7 and add reference implementation for manifest changes

- src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.pme.json
> Fix role prod

- scripts/Release/rotate_function_keys.ps1
Simplify azure functions app keys rotation script by calling `az functionapp keys set` instead of handrolling the REST calls.
> Simplify rotation script

- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.int.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.pme.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.ppe.json
- src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.test.json
Set up function key rotation release. Adding deployment OIDs to update the keys on KeyVault and deleting old service principals
> Add managed identities OIDs to KeyVault

- pipelines/templates/restore-build-publish-test.yml
- pipelines/winget-cli-restsource-ci-pr.yml
- pipelines/winget-cli-restsource-ci.yml
- src/WinGet.RestSource.Fuzzing/Fuzzer.cs
- src/WinGet.RestSource.Fuzzing/OneFuzzConfig.json
- src/WinGet.RestSource.Fuzzing/WinGet.RestSource.Fuzzing.csproj
- src/WinGet.RestSource.sln
Creates fuzzing artifacts which will be submitted to OneFuzz for testing our fileparsing logic.
> Add fuzzing project and submit artifacts in pipeline

- Tools/PowershellModule/src/Library/New-ARMParameterObjects.ps1
When secondary region is not available, do not add to location list.
> Handle cases when secondary region is not available

- .config/tsaoptions.json
- Tools/PowershellModule/src/Microsoft.WinGet.RestSource.psd1
- pipelines/publish-powershell-module.yml
- src/WinGet.RestSource.sln
Also removed prerelease tag for publishing as GA.
> Use release job for publishing to PS Gallery

- pipelines/publish-powershell-module.yml
- pipelines/templates/sign-azure-function.yml
- src/WinGet.RestSource.sln
Test run without actual publishing
https://microsoft.visualstudio.com/Apps/_build/results?buildId=126912546&view=results
> Fix release signing
