src/WinGet.RestSource.Functions/PackageManifestFunctions.cs, src/WinGet.RestSource/Constants/Enumerations/PackageMatchFields.cs, src/WinGet.RestSource/Constants/QueryConstants.cs, src/WinGet.RestSource/Cosmos/CosmosDataStore.cs, src/WinGet.RestSource/Models/Arrays/Agreements.cs, src/WinGet.RestSource/Models/Arrays/AppsAndFeaturesEntries.cs, src/WinGet.RestSource/Models/Arrays/Markets.cs, src/WinGet.RestSource/Models/Arrays/UnsupportedOSArchitectures.cs, src/WinGet.RestSource/Models/Objects/AppsAndFeatures.cs, src/WinGet.RestSource/Models/Objects/Markets.cs, src/WinGet.RestSource/Models/Objects/SourceAgreement.cs, src/WinGet.RestSource/Models/Schemas/Installer.cs, src/WinGet.RestSource/Models/Schemas/Locale.cs, src/WinGet.RestSource/Validators/DateTimeValidators/ApiDateTimeValidator.cs, src/WinGet.RestSource/Validators/DateTimeValidators/ReleaseDateValidator.cs, src/WinGet.RestSource/Validators/EnumValidators/PackageMatchFieldValidator.cs, src/WinGet.RestSource/Validators/EnumValidators/UnsupportedOSArchitecturesValidator.cs, src/WinGet.RestSource/Validators/StringValidators/AgreementLabelValidator.cs, src/WinGet.RestSource/Validators/StringValidators/AgreementValidator.cs, src/WinGet.RestSource/Validators/StringValidators/DisplayAndPublisherNameValidator.cs, src/WinGet.RestSource/Validators/StringValidators/DisplayVersionValidator.cs, src/WinGet.RestSource/Validators/StringValidators/MSStoreProductIdentifierValidator.cs, src/WinGet.RestSource/Validators/StringValidators/MarketValidator.cs, src/WinGet.RestSource/Validators/StringValidators/ReleaseNotesValidator.cs
This PR contains the following changes:
- New Json fields from V1.1 Installer and Locale schema.
- Market query and filter.
Tests:
- Manually validated Installer, locale and package manifests endpoints to ensure database gets the new field values.
- Validated Market query param returns only applicable results in GET package manifest endpoints and search endpoint.
Next PR:
- Will add Information Schema changes in the next PR.
=> Rest Schema V1.1 changes - Part1

documentation/WinGet-1.1.0.yaml, src/WinGet.RestSource/Models/Arrays/ExpectedReturnCodes.cs, src/WinGet.RestSource/Models/Objects/ExpectedReturnCode.cs, src/WinGet.RestSource/Models/Schemas/Installer.cs, src/WinGet.RestSource/Validators/DateTimeValidators/ReleaseDateValidator.cs, src/WinGet.RestSource/Validators/EnumValidators/ElevationRequirementValidator.cs, src/WinGet.RestSource/Validators/EnumValidators/ExpectedReturnCodeResponseValidator.cs
- This PR contains the Schema changes and ref implementation changes for V1.1 fields that were finalized recently.
- ElevationRequirement and Installer ExpectedReturnCodes
Tests
- Manually tested with Postman and verified all the validation rules are honored for both the fields added. All the Get, put and post methods store and retrieve fields as expected.
=> Add expected return codes and elevation requirement fields

documentation/WinGet-1.1.0.yaml, src/WinGet.RestSource/Models/Arrays/ExpectedReturnCodes.cs, src/WinGet.RestSource/Models/Arrays/InstallerSuccessCodes.cs, src/WinGet.RestSource/Models/Objects/ExpectedReturnCode.cs
- My previous PR contained the installer return code maximum value with a missing number. This PR fixes that.
- Tested minimum and maximum bound is validated for installer return codes.
=> Update max value of installer return code

src/WinGet.RestSource/Models/Schemas/ManifestSearchResponse.cs, src/WinGet.RestSource/Models/Schemas/PackageManifest.cs, src/WinGet.RestSource/Validators/StringValidators/LicenseValidator.cs, src/WinGet.RestSource/Validators/StringValidators/LocaleValidator.cs, src/WinGet.RestSource/Validators/StringValidators/PackageNameValidator.cs, src/WinGet.RestSource/Validators/StringValidators/PublisherValidator.cs, src/WinGet.RestSource/Validators/StringValidators/ShortDescriptionValidator.cs, src/WinGet.RestSource/Validators/StringValidators/TagValidator.cs
This change:
1. Revises app groupings on search to reflect that versions from the same package ID may not have the same name/publisher.
2. Updates a variety of validator rules to allow for nulls or looser pattern matches as the yaml schema allows.
3. Updates package manifest to support extended versions.
=> Update implementation to more closely align with wingte yaml rules

Tools/PowershellModule/src/Library/Add-WinGetManifest.ps1, Tools/PowershellModule/src/Library/Get-WinGetManifest.ps1, Tools/PowershellModule/src/Library/Remove-WinGetManifest.ps1, pipelines/templates/copy-and-publish-powershell.yml
This change aligns the cmdlet parameter with the actual package identifier variable name.
It also tweaks the output folders for the build.
=> Rename manifest identifier and output folder

README.md, pipelines/templates/restore-build-publish-test.yml, pipelines/templates/run-integrationtests.yml, pipelines/templates/run-unittests.yml, pipelines/winget-cli-restsource-ci-pr.yml, src/WinGet.RestSource.Functions/PackageFunctions.cs, src/WinGet.RestSource.Functions/PackageManifestFunctions.cs, src/WinGet.RestSource.IntegrationTest/Common/TestsBase.cs, src/WinGet.RestSource.IntegrationTest/Test.runsettings.template.json, src/WinGet.RestSource.IntegrationTest/Tests/Functions/FunctionsTests.cs, src/WinGet.RestSource.IntegrationTest/Tests/Winget/WingetTests.cs, src/WinGet.RestSource.IntegrationTest/WinGet.RestSource.IntegrationTest.csproj, src/WinGet.RestSource.UnitTest/Tests/RestSource/Cosmos/CosmosDataStoreTests.cs, src/WinGet.RestSource.Utils/Models/Schemas/ManifestSearchRequest.cs, src/WinGet.RestSource.Utils/Models/Schemas/ManifestSearchResponse.cs, src/WinGet.RestSource.sln
- Adding two new integration test suites
- One tests directly against the REST endpoints, and includes write-operations
- One tests indirectly against the REST endpoints by calling into the winget client
- Modifies the build pipeline to run new tests. The write-operation tests aren't run by default, we may decide to change this later. I had to update the pipeline to windows-2022 to get winget to run packaged.
- Fixed a bug where the Package* GET apis weren't correctly using the continuationToken.
=> Adding integration tests

src/NuGet.config
The NuGet configuration was using a internal Microsoft NuGet source, which meant nobody outside who was trying to use this code could restore successfully. 
The public repo appears to contain all of the necessary packages, so restore is successful.
=> Changed NuGet configuration to use public repository.

src/WinGet.RestSource.IntegrationTest/Tests/Winget/WingetTests.cs
`result.StandardOutput` and `result.StandardError` can never be null, so `string.IsNullOrWhiteSpace(...)` (or maybe `string.IsNullOrEmpty(...)` to be less greedy) is a better fit.
=> Fix CliWrap usage

Tools/PowershellModule/src/Library/New-ARMObjects.ps1, Tools/PowershellModule/src/Library/New-ARMParameterObject.ps1, pipelines/winget-cli-restsource-ci.yml, src/WinGet.RestSource.sln
This change adjusts the object id lookup logic to distinguish between a user and service principal context.
This enables running the scripts from CI/CD environments.
Additionally, it increases the verbosity of verbose logging.
=> Revise Scripts to support running from a service principal context

README.md, SECURITY.md, Tools/PowershellModule/doc/new-winget-rest-source-azure.md
Fixed a link along with removed `en-US` in links (excluding the `src/` folder).
I know not every link has different languages, but some do, so it's better to have the standard use of Microsoft links to be without `en-US`. If there is no other language, it will redirect to `en-US` anyway.
=> Fixed link + removed en-US in links

src/WinGet.RestSource.Functions/SourceFunctions.cs, src/WinGet.RestSource.Functions/Startup.cs, src/WinGet.RestSource.UnitTest/Tests/AzFunctions/SourceFunctionsTests.cs, src/WinGet.RestSource.UnitTest/Tests/RestSource/Helpers/RestSourceTriggerFunctionsTests.cs, src/WinGet.RestSource.UnitTest/Tests/RestSource/Operation/RebuildTests.cs, src/WinGet.RestSource.UnitTest/Tests/RestSource/Operation/UpdateTests.cs, src/WinGet.RestSource/Helpers/RestSourceTriggerFunctions.cs, src/WinGet.RestSource/Interfaces/IRebuild.cs, src/WinGet.RestSource/Interfaces/IRestSourceTriggerFunction.cs, src/WinGet.RestSource/Interfaces/IUpdate.cs, src/WinGet.RestSource/Operations/Rebuild.cs, src/WinGet.RestSource/Operations/Update.cs
Before we read the environment variable for the azure function host key in the startup of the function app. If the key gets rotated, the new value won't get refreshed until a new deployment is made.
Fix is to read the env var when is needed.
=> Fix reading function key

src/WinGet.RestSource.UnitTest/Tests/RestSource/Helpers/RestSourceTriggerFunctionsTests.cs, src/WinGet.RestSource/Helpers/RestSourceTriggerFunctions.cs
Doing operations on packages that end with .browser will result in a 404.
Adding a / at the end fix it. 
We will look in the future on a better fix.
=> Add / at the end for internal REST endpoint calls

README.md, Tools/PowershellModule/doc/PowerShell/New-WinGetSource.md, Tools/PowershellModule/src/Library/New-ARMParameterObject.ps1, Tools/PowershellModule/src/Library/New-WinGetSource.ps1, src/WinGet.RestSource.Infrastructure/README.MD, src/WinGet.RestSource.Utils/WinGet.RestSource.Utils.csproj
=> Fix documentation bugs. Fix duplicate reference.

documentation/WinGet-1.4.0.yaml, src/WinGet.RestSource.Utils/Models/Arrays/Protocols.cs
Related to: https://github.com/microsoft/winget-cli/issues/2600
Updates the max number of items for the Protocols field from 16 to 64.
=> Update protocol max items to 64

documentation/WinGet-1.0.0.yaml, documentation/WinGet-1.1.0.yaml, documentation/WinGet-1.4.0.yaml
Hi Microsoft,
Look like  `Locale` API URL path are incorrect at API Documentation
`/packages/{PackageIdentifier}/versions/{PackageVersion}/locale`
`/packages/{PackageIdentifier}/versions/{PackageVersion}/locale/{PackageLocale}`
should be 
`/packages/{PackageIdentifier}/versions/{PackageVersion}/locales`
`/packages/{PackageIdentifier}/versions/{PackageVersion}/locales/{PackageLocale}`
missing `s`
Thanks.
=> Fix Locale API url path are incorrect at API Documentation

Tools/PowershellModule/src/Library/New-WinGetSource.ps1, src/Microsoft.WindowsPackageManager.Rest/Microsoft.WindowsPackageManager.Rest.csproj, src/WinGet.RestSource.AppConfig/WinGet.RestSource.AppConfig.csproj, src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj, src/WinGet.RestSource.IntegrationTest/WinGet.RestSource.IntegrationTest.csproj, src/WinGet.RestSource.PowershellSupport/WinGet.RestSource.PowershellSupport.csproj, src/WinGet.RestSource.UnitTest/Common/TestCollateralHelper.cs, src/WinGet.RestSource.UnitTest/WinGet.RestSource.UnitTest.csproj, src/WinGet.RestSource.Utils/WinGet.RestSource.Utils.csproj, src/WinGet.RestSource/WinGet.RestSource.csproj
* Azure Function project (and all its dependencies) migrated to .NET 6 and Functions Runtime 4.
=> Porting to .NET 6 and Azure Functions Runtime 4

pipelines/templates/restore-build-publish-test.yml, pipelines/winget-cli-restsource-ci-pr.yml, pipelines/winget-cli-restsource-ci.yml, src/Microsoft.WindowsPackageManager.Rest/Microsoft.WindowsPackageManager.Rest.csproj, src/WinGet.RestSource.sln
Previous commit breaks the build with:
Targeting .NET 6.0 in Visual Studio 2019 is not supported.
Try retarget to VS 2022
=> Fix pipeline build break

Tools/PowershellModule/src/Library/Convert-YAMLToJSON.ps1, Tools/PowershellModule/src/Library/WingetClasses.ps1, Tools/PowershellModule/src/Microsoft.WinGet.Source.psd1, Tools/PowershellModule/src/Microsoft.WinGet.Source.psm1, pipelines/winget-cli-restsource-ci-pr.yml
Support for converting YAML to JSON Package Manifests
=> Support for converting YAML to JSON Package Manifests

src/WinGet.RestSource.PowershellSupport/YamlToRestConverter.cs, src/WinGet.RestSource.UnitTest/Tests/PowerShellSupport/YamlToRestConverterTests.cs
The latest update to WinGetUtils no longer has `WinGetUtilWrapperManifest.ValidateManifest`. This PR fixes that issue by updating to calling WinGetValidateV3
=> Fix build errors by calling WinGetValidateV3 

src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.pme.json
context:
Persistent Access to production *ME tenant resources:
Violates Least Privileged and Zero Trust Principles imposes risks for data exfiltration by adversaries in the event of a lateral pivot.
=> Remove secrets list for security groups

.gitignore, scripts/Release/service_principals_roles.ps1, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.int.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.int.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.pme.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.pme.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.ppe.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.ppe.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.test.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.test.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.int.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.pme.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.ppe.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.test.json, src/WinGet.RestSource.Infrastructure/Templates/AzureFunction/azurefunction.json
This change removes the use of the Storage Account connection string in Azure Funcions for AzureWebJobsStorage. This is not a full move to managed identities because WEBSITE_CONTENTAZUREFILECONNECTIONSTRING still doesn't support them.
=> Use managed identities for AzureWebJobsStorage

scripts/Release/saksecret_refresh.ps1, src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj, src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.int.json, src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.ppe.json
This PR
1. Fix rotation script. While we are in the process of moving away from connection strings, we still need them while Azure Files implement support using managed identity. The rotation script is outdated as `az keyvault storage` is deprecated so the command doesn't exist in the az cli of the agents. This cmd was useful as it gives you which is the active key to be used for the connection string. Instead we just figure out which one is the oldest one set it in the key vault.
2. Add new OIDs for service principals
3. Update nuget package for Azure Durable functions.
=> Update rotation script and Azure Durable functions

src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj
Azure Cosmos DB extension version 3.x for Azure Functions, and the underlying SDK, will be retired on 31 August 2024. Update to extension version 4.x, which is built on the newer Microsoft.Azure.Cosmos SDK,
=> Update Cosmos db package to 4.x

scripts/Release/service_principals_roles.ps1, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.deployment.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.int.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.int.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.pme.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.pme.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.ppe.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.ppe.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/AzureFunction/azurefunction.test.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/KeyVault/keyvault.test.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.int.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.pme.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.ppe.json, src/WinGet.RestSource.Infrastructure/Parameters/Roles/roles.test.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.int.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.int.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.pme.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.pme.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.ppe.centus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.ppe.westus.json, src/WinGet.RestSource.Infrastructure/Parameters/StorageAccount/storageaccount.test.westus.json, src/WinGet.RestSource.Infrastructure/Templates/AzureFunction/azurefunction.json, src/WinGet.RestSource.Infrastructure/Templates/StorageAccount/storageaccount.json
Azure Storage File Share doesn’t currently support managed identities. This is used by the `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` environment variable and is required for azure functions that use a consumption plan.
There is a work around to use `WEBSITE_RUN_FROM_PACKAGE` where one needs to upload the azure function zip package into an storage account that is accessible to the function app. The main downside is that there is a 15 seconds cold start.
For this to work the release needs to be modified to not use the AzFunc deploy task as it is not supported. We have a task group that is specialized in azure function deployment. I modified that task with the following.
- Upload the zip package into the storage account used for the function. I'm uploading it into a deployments container …
=> Use WEBSITE_RUN_FROM_PACKAGE in azure functions for deployment

src/WinGet.RestSource.AppConfig/WinGet.RestSource.AppConfig.csproj, src/WinGet.RestSource.Functions/SourceFunctions.cs, src/WinGet.RestSource.Functions/Startup.cs, src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj, src/WinGet.RestSource.UnitTest/Tests/AzFunctions/SourceFunctionsTests.cs, src/WinGet.RestSource/WinGet.RestSource.csproj
The following packages were updated:
- Microsoft.Extensions.Configuration.AzureAppConfiguration from 4.1.0 to 7.2.0
- Microsoft.Extensions.Configuration.Binder from 3.1.12 to 6.0.0
- Microsoft.Extensions.DependencyInjection from 3.1.12 to 6.0.1
- Azure.Identity from 1.11.3 to 1.11.4
The following packages were explicitly updated as the flagged version is a dependency of another pacakge:
- System.Data.SqlClient 4.8.6
- Azure.Security.KeyVault.Secrets 4.6.0
Other changes:
- The `TelemetryConfiguration` constructor with the instrumentation key is now obsolete. Instead one must set the connection string.
- There are more static analysis for Azure functions. In this case, we cannot use a member object in an orchestrator. Removed calls to `telemetryClient`. We are still going to get telemetry …
=> Fix Component Governance alerts

pipelines/publish-powershell-module.yml
Change the release pipeline to use OneBranch instead of 1ES Pipeline Templates. This allows us to use their registration for ESRP instead of having our own.
=> Use OneBranch for signing

Tools/PowershellModule/doc/WingetRestSource.md
The string "PS C:\>" while visibly makes sense, it prevents you from doing copy / paste with out going back and removing the string. 
With this change, people can more easily copy / paste the powershell command.
=> Removed 'PS C:\' since that broke the copy / paste experience

Tools/PowershellModule/src/Library/WinGetManifest.ps1, documentation/WinGet-1.10.0.yaml, pipelines/templates/copy-and-publish-powershell.yml, src/Microsoft.WindowsPackageManager.Rest/Microsoft.WindowsPackageManager.Rest.csproj, src/WinGet.RestSource.AppConfig/WinGet.RestSource.AppConfig.csproj, src/WinGet.RestSource.Functions/WinGet.RestSource.Functions.csproj, src/WinGet.RestSource.Fuzzing/WinGet.RestSource.Fuzzing.csproj, src/WinGet.RestSource.IntegrationTest/WinGet.RestSource.IntegrationTest.csproj, src/WinGet.RestSource.PowershellSupport/WinGet.RestSource.PowershellSupport.csproj, src/WinGet.RestSource.UnitTest/WinGet.RestSource.UnitTest.csproj, src/WinGet.RestSource.Utils/Constants/ApiConstants.cs, src/WinGet.RestSource.Utils/Constants/Enumerations/AuthenticationType.cs, src/WinGet.RestSource.Utils/Models/Objects/Authentication.cs, src/WinGet.RestSource.Utils/Models/Schemas/Information.cs, src/WinGet.RestSource.Utils/Models/Schemas/Installer.cs, src/WinGet.RestSource.Utils/Utils/PackageManifestUtils.cs, src/WinGet.RestSource.Utils/Validators/EnumValidators/AuthenticationTypeValidator.cs, src/WinGet.RestSource.Utils/WinGet.RestSource.Utils.csproj, src/WinGet.RestSource/WinGet.RestSource.csproj
3 commits for easier review of schema change. Commit 2 shows the schema changes in 1.10. Basically the change to add support for installer authentication and minor reordering of the schema definitions.
With this change, Csharp language version is updated to 12 as it's the default language version for .net 8.
=> Add support for 1.10 manifest schema

src/WinGet.RestSource.Utils/Models/Arrays/Capabilities.cs, src/WinGet.RestSource.Utils/Models/Arrays/RestrictedCapabilities.cs
=> RestrictedCapabilities & Capabilities Validator fixes
